bombermine:
  ctfgame:
    max_team_players: 5
    respawn_cooldown: 10
  teams:
  - id: red
    name: Equipe des rouges
    spawn: world/0/0/0
    max: 5
    flagType: IRON_ORE
  - id: blue
    name: Equipe des bleus
    spawn: world/0/0/0
    max: 5
    flagType: IRON_ORE

  faster:
    materials: [BRICK]
    acceleration: 1.4