name: Bombermine
main: com.github.myorama.bombermine.Bombermine
version: 0.1

commands:
  bm:
    description: This is the base command giving help on sub commands
    permission: bombermine.bm
    usage: /bm