name: Bombermine
main: com.github.myorama.bombermine.Bombermine
version: 0.1

commands:
  bm:
    description: This is the base command giving help for all bombermine commands

permissions:
  bombermine.*:
    description: Give all bombermine permissions (be careful, some are admin reserved)
    children:
      bombermine.player: true
      bombermine.moderator: true
      bombermine.admin: true
  bombermine.admin:
    description: Give admin permissions. Allow map creation commands
    default: op
  bombermine.moderator:
    description: Give moderator permissions. Allow CTF game management
    default: op
  bombermine.player:
    description: Give classic player permissions
    default: true